version: '3.8'

services:
  app:
    build: ./app
    container_name: jokes-app
    restart: always

  nginx:
    image: nginx:alpine
    container_name: jokes-app-webserver
    ports:
      - "80:8080"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    restart: always